### PR TITLE
Code: Added Test Mode

### PR DESCRIPTION
**Pull request by OliverOrd**
Test Mode allows users to make sure the bot is working properly without having to actually pay for products. It tries to get to the final checkout stage. If the payment button could be pressed successfully then the test is a success, otherwise, the test is a failure.

I have also added some time.sleep() where I think it will improve stability.

### CODE REVIEW

**Comment by abayomi185** [comment]
Hey Oliver, why did you increase the sleep duration?

**Comment by abayomi185** [comment]
closes #7

**Comment by OliverOrd** [comment]
Hi, 

I increased sleep duration as I found that sometimes it takes some time between clicking "Card" and the payment page getting reached and the bot would sometimes timeout without a higher sleep value

**Comment by abayomi185** [comment]
Cool

**Pull request merged**
