### PR TITLE
Merge pull request #2 from abayomi185/main

### PR DESCRIPTION
**Pull request by OliverOrd**
bringing my branch up to date with original

### CODE REVIEW

**Comment by abayomi185** [comment]
Did you replace the card payment method with PayPal?

**Comment by OliverOrd** [comment]
I created an implementation that pays with Paypal but it isn't much use due to 2 factor authentication

**Comment by OliverOrd** [comment]
I didn't mean to try and merge with yours. I just tried to get it working on my fork lol

**Comment by abayomi185** [comment]
Ah okay. Cool

Nice placeholders too.

**Pull request closed without merging**
